<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
    <PackageReference Include="Moq" Version="4.20.70" />
    <PackageReference Include="FluentAssertions" Version="6.12.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CartService\CartService.Domain\CartService.Domain.csproj" />
    <ProjectReference Include="..\DeliveryService\DeliveryService.Domain\DeliveryService.Domain.csproj" />
    <ProjectReference Include="..\OrderReadService\OrderReadService.Infrastructure\OrderReadService.Infrastructure.csproj" />
    <ProjectReference Include="..\Shared\Shared.csproj" />
    <ProjectReference Include="..\LocationTrackingService\LocationTrackingService.csproj" />
    <ProjectReference Include="..\PaymentService\PaymentService.Domain\PaymentService.Domain.csproj" />
    <ProjectReference Include="..\PaymentService\PaymentService.Application\PaymentService.Application.csproj" />
    <ProjectReference Include="..\PaymentService\PaymentService.Infrastructure\PaymentService.Infrastructure.csproj" />
    <ProjectReference Include="..\CatalogService\CatalogService.Domain\CatalogService.Domain.csproj" />
    <ProjectReference Include="..\CatalogService\CatalogService.Application\CatalogService.Application.csproj" />
    <ProjectReference Include="..\CatalogService\CatalogService.Infrastructure\CatalogService.Infrastructure.csproj" />
    <ProjectReference Include="..\CatalogReadService\CatalogReadService.Application\CatalogReadService.Application.csproj" />
    <ProjectReference Include="..\CatalogReadService\CatalogReadService.Infrastructure\CatalogReadService.Infrastructure.csproj" />
    <ProjectReference Include="..\OrderService\OrderService.Domain\OrderService.Domain.csproj" />
    <ProjectReference Include="..\OrderService\OrderService.Infrastructure\OrderService.Infrastructure.csproj" />
    <ProjectReference Include="..\OrderService\OrderService.Application\OrderService.Application.csproj" />
    <ProjectReference Include="..\CourierService\CourierService.Domain\CourierService.Domain.csproj" />
    <ProjectReference Include="..\CourierService\CourierService.Application\CourierService.Application.csproj" />
    <ProjectReference Include="..\InventoryService\InventoryService.Domain\InventoryService.Domain.csproj" />
    <ProjectReference Include="..\InventoryService\InventoryService.Application\InventoryService.Application.csproj" />
    <ProjectReference Include="..\InventoryService\InventoryService.Infrastructure\InventoryService.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="9.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.0" />
    <PackageReference Include="Elastic.Clients.Elasticsearch" Version="8.10.0" />
    <PackageReference Include="StackExchange.Redis" Version="2.11.8" />
  </ItemGroup>

</Project>
